import json
import logging
from pathlib import Path
from typing import Any, Dict, List

from ..config import CONTRACTS_LOG_PATH as _LOG_PATH

log = logging.getLogger(__name__)

# Priority labels
_LABEL_HIGH   = "høj"
_LABEL_MEDIUM = "medium"
_LABEL_LOW    = "lav"


def _label(score: int) -> str:
    if score >= 80:
        return _LABEL_HIGH
    if score >= 65:
        return _LABEL_MEDIUM
    return _LABEL_LOW


# ── Rich static dataset per city ──────────────────────────────────

_CONTRACTS: Dict[str, List[Dict]] = {

    "Horsens": [
        {
            "name": "Horsens Sygehus",
            "type": "Hospital",
            "address": "Sundvej 30, 8700 Horsens",
            "phone": "+45 78 43 10 00",
            "website": "horsens.rm.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Ca. 400.000 patientbesøg/år",
            "potential_score": 92,
            "score_explanation": "Stort hospital med høj patientvolumen, daglig transportbehov til/fra, kommunalt udbud muligt via Region Midtjylland",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt indkøbsafdelingen – spørg efter transport-udbud og tilbyd månedlig aftale",
            "contact_title": "Indkøbsafdeling / Transportkoordinator",
        },
        {
            "name": "Horsens Kommune",
            "type": "Kommune",
            "address": "Rådhustorvet 4, 8700 Horsens",
            "phone": "+45 76 29 29 29",
            "website": "horsens.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 90.000 borgere, social transport budget",
            "potential_score": 88,
            "score_explanation": "Kommunal social transport til ældre og handicappede, faste kontrakter via Udbud.dk, stabilt volumen",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud på næste udbud via Udbud.dk – hold øje med udbudsportalen",
            "contact_title": "Social- og Sundhedsforvaltningen",
        },
        {
            "name": "Plejehjemmet Lunden",
            "type": "Plejehjem",
            "address": "Lundvej 12, 8700 Horsens",
            "phone": "+45 76 29 50 00",
            "website": "horsens.dk/plejehjem",
            "industry": "Ældrepleje",
            "size_hint": "Ca. 80 beboere, daglige lægebesøg og transport",
            "potential_score": 83,
            "score_explanation": "Fast behov for transport til læge, hospital og aktiviteter – typisk fast kontrakt over 1-2 år",
            "opportunity": "Fast plejehjem-kørsel til læge og hospital",
            "action_da": "Kontakt plejehjemslederen og tilbyd fast ugentlig kørsel",
            "contact_title": "Plejehjemsleder / Afdelingssygeplejerske",
        },
        {
            "name": "Hotel Opus Horsens",
            "type": "Hotel",
            "address": "Bryggerivej 10, 8700 Horsens",
            "phone": "+45 75 62 29 00",
            "website": "hotelopus.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "129 værelser, primært erhvervsgæster",
            "potential_score": 86,
            "score_explanation": "Stort erhvervshotel, mange konferencegæster, lufthavn-transfer til Billund er hyppig behov",
            "opportunity": "Airport transfer + konferencegæstetransport",
            "action_da": "Ring og spørg efter events-koordinator – tilbyd fast transfer-rate til Billund Lufthavn",
            "contact_title": "Events-koordinator / Receptionen",
        },
        {
            "name": "Scandic Bygholm Park",
            "type": "Hotel",
            "address": "Schüttesvej 6, 8700 Horsens",
            "phone": "+45 75 62 23 33",
            "website": "scandichotels.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "76 værelser, konferencefaciliteter",
            "potential_score": 78,
            "score_explanation": "Kædehotel med faste konferencer, god synlighed, transfer-behov til stationer og lufthavn",
            "opportunity": "Gæstetransport & stationstransfer",
            "action_da": "Kontakt hotelchefen – tilbyd fast samarbejde og visitkort i lobby",
            "contact_title": "Hotelchef / Receptionen",
        },
        {
            "name": "CASA Arena Horsens",
            "type": "Venue",
            "address": "Langmarksvej 65, 8700 Horsens",
            "phone": "+45 76 29 30 00",
            "website": "casaarena.dk",
            "industry": "Sport & Events",
            "size_hint": "10.400 tilskuere, 50+ events/år",
            "potential_score": 82,
            "score_explanation": "Stor multiarena med fodboldbane og koncerter – massiv taxiefterspørgsel ved events, sæsonaftale giver stabilt volumen",
            "opportunity": "Event- og kampagnetransport (sæsonaftale)",
            "action_da": "Kontakt event-koordinatoren – tilbyd dedikeret taxa-service ved alle events",
            "contact_title": "Event-koordinator / Driftschef",
        },
        {
            "name": "Sønderbro Restaurant & Café",
            "type": "Restaurant",
            "address": "Sønderbrogade 18, 8700 Horsens",
            "phone": "+45 75 61 22 11",
            "website": "soenderbro.dk",
            "industry": "Restauration",
            "size_hint": "Populær byrestaurant, mange selskaber og aftenfejringer",
            "potential_score": 69,
            "score_explanation": "Selskaber og firmamiddage skaber behov for hjemkørsel – visitkort ved kassen giver organisk trafik",
            "opportunity": "Hjemkørsel efter selskaber og middage",
            "action_da": "Aftal visitkort-placering ved kassen og mulighed for fast aftale ved firmaarrangementer",
            "contact_title": "Restaurantchef / Ejer",
        },
        {
            "name": "CLEAN (Biogasklynge)",
            "type": "Virksomhed",
            "address": "Horsens Erhvervspark, 8700 Horsens",
            "phone": "+45 87 55 00 00",
            "website": "cleancluster.dk",
            "industry": "Cleantech & Energi",
            "size_hint": "Ca. 200 medarbejdere, internationale gæster",
            "potential_score": 74,
            "score_explanation": "Erhvervspark med internationale partnere, airport-transfer til Billund og Aarhus, potentiel fast aftale",
            "opportunity": "Medarbejdertransport & internationale gæster",
            "action_da": "Book møde med HR eller travel manager – tilbyd fast firmataxa-aftale",
            "contact_title": "HR / Travel Manager",
        },
        {
            "name": "VIA University College Horsens",
            "type": "Uddannelse",
            "address": "Chr. M. Østergaards Vej 4, 8700 Horsens",
            "phone": "+45 87 55 10 00",
            "website": "via.dk",
            "industry": "Videregående uddannelse",
            "size_hint": "Ca. 5.000 studerende, mange pendlere",
            "potential_score": 70,
            "score_explanation": "Mange studerende og ansatte der pendler, introuge-kørsel og personaletransport",
            "opportunity": "Studerende & personaletransport",
            "action_da": "Kontakt administrationen om aftale til introuge og personalearrangementer",
            "contact_title": "Campus-administrator / Studieservice",
        },
        {
            "name": "Lægeklinik Horsens Centrum",
            "type": "Klinik",
            "address": "Søndergade 14, 8700 Horsens",
            "phone": "+45 75 62 00 50",
            "website": "laegekliniken-horsens.dk",
            "industry": "Sundhed & Lægehjælp",
            "size_hint": "Ca. 2.500 tilknyttede patienter",
            "potential_score": 72,
            "score_explanation": "Ældre og gangbesværede patienter har brug for fast hjemtransport – fast aftale med klinikken giver troværdighed",
            "opportunity": "Patient-kørsel & hjemtransport",
            "action_da": "Kontakt kliniklederen og tilbyd visitkort til receptionen samt fast patient-kørsel",
            "contact_title": "Klinikleder / Receptionen",
        },
    ],

    "Aarhus": [
        {
            "name": "Aarhus Universitetshospital (AUH)",
            "type": "Hospital",
            "address": "Palle Juul-Jensens Boulevard 99, 8200 Aarhus N",
            "phone": "+45 78 45 00 00",
            "website": "auh.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Danmarks næststørste hospital, 1 mio+ patientkontakter/år",
            "potential_score": 94,
            "score_explanation": "Enormt hospital med massivt dagligt transportbehov, regionalt udbud muligt, mange pårørende og ambulante patienter",
            "opportunity": "Patienttransport-kontrakt (regionalt udbud)",
            "action_da": "Kontakt Region Midtjyllands indkøbsafdeling – tilmeld jer udbudslisten for patienttransport",
            "contact_title": "Indkøbsafdeling / Patientsekretariatet",
        },
        {
            "name": "Aarhus Kommune",
            "type": "Kommune",
            "address": "Rådhuspladsen 2, 8000 Aarhus C",
            "phone": "+45 89 40 20 00",
            "website": "aarhus.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 350.000 borgere, stort social transport budget",
            "potential_score": 90,
            "score_explanation": "Landets næststørste kommune, massive udbud på social transport og handicapkørsel",
            "opportunity": "Social transport & handicapkørsel (EU-udbud)",
            "action_da": "Hold øje med Udbud.dk under 'Aarhus Kommune transport' – afgiv tilbud på næste runde",
            "contact_title": "Socialforvaltning / Udbudsansvarlig",
        },
        {
            "name": "Bestseller A/S (HQ)",
            "type": "Virksomhed",
            "address": "Fredskovhellet 3, 7330 Brande (HQ) / Aarhus",
            "phone": "+45 99 42 00 00",
            "website": "bestseller.com",
            "industry": "Mode & Retail",
            "size_hint": "20.000+ ansatte globalt, exec transport behov",
            "potential_score": 84,
            "score_explanation": "Stor dansk virksomhed med internationale gæster og executive transport behov til Billund og Aarhus Lufthavn",
            "opportunity": "Executive transport & lufthavn-transfer",
            "action_da": "Kontakt travel manager eller facilities – tilbyd fast exec-taxiaftale",
            "contact_title": "Travel Manager / Facilities",
        },
        {
            "name": "Hotel Royal Aarhus",
            "type": "Hotel",
            "address": "Store Torv 4, 8000 Aarhus C",
            "phone": "+45 86 12 00 11",
            "website": "hotelroyal.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "68 eksklusive værelser, centralt placeret",
            "potential_score": 82,
            "score_explanation": "Eksklusivt hotel i centrum, velhavende gæster, regelmæssige lufthavn-transfers til Aarhus Airport",
            "opportunity": "Gæstetransport & airport-transfer",
            "action_da": "Kontakt receptionen – tilbyd fast rate-aftale og visitkort i lobbyen",
            "contact_title": "Direktør / Receptionen",
        },
        {
            "name": "Scandic The Mayor",
            "type": "Hotel",
            "address": "Banegårdspladsen 14, 8000 Aarhus C",
            "phone": "+45 87 32 01 00",
            "website": "scandichotels.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "162 værelser, klar erhvervsprofil ved banegården",
            "potential_score": 79,
            "score_explanation": "Velbeliggende ved banegården, mange erhvervsgæster, lufthavn-transfer efterspurgt",
            "opportunity": "Erhvervsgæstetransport & airport-transfer",
            "action_da": "Kontakt hotelchefen – tilbyd fast samarbejde og pjecer i receptionen",
            "contact_title": "Hotelchef / Front desk manager",
        },
        {
            "name": "Restaurant Nordisk Spisehus",
            "type": "Restaurant",
            "address": "M.P. Bruuns Gade 31, 8000 Aarhus C",
            "phone": "+45 86 17 70 99",
            "website": "nordiskspisehus.dk",
            "industry": "Restauration",
            "size_hint": "Populær gourmetrestaurant, mange firmamiddage",
            "potential_score": 67,
            "score_explanation": "Aftenfejringer og firmamiddage genererer hjemkørselsbehov – visitkort ved indgangen er et naturligt skridt",
            "opportunity": "Hjemkørsel efter firmamiddage og fejringer",
            "action_da": "Aftal visitkort og QR-kode til taxa-booking ved restauranten",
            "contact_title": "Restaurantchef / Ejer",
        },
        {
            "name": "Ceres Park (AGF Fodbold)",
            "type": "Venue",
            "address": "Stadion Allé 70, 8000 Aarhus C",
            "phone": "+45 89 38 00 00",
            "website": "agf.dk",
            "industry": "Sport & Events",
            "size_hint": "20.000 tilskuere, Superliga-kampe",
            "potential_score": 80,
            "score_explanation": "Store Superliga-kampe og events skaber massiv taxiefterspørgsel – sæsonaftale med AGF er mulig",
            "opportunity": "Kampagnekørsel & event-transport (sæsonaftale)",
            "action_da": "Kontakt AGF's event-afdeling om officielt taxi-partnersamarbejde",
            "contact_title": "Event-manager / Kommerciel afdeling",
        },
        {
            "name": "Plejehjemmet Thorvaldsensgade",
            "type": "Plejehjem",
            "address": "Thorvaldsensgade 28, 8000 Aarhus C",
            "phone": "+45 89 40 35 00",
            "website": "aarhus.dk/plejehjem",
            "industry": "Ældrepleje",
            "size_hint": "Ca. 60 beboere",
            "potential_score": 81,
            "score_explanation": "Kommunalt plejehjem med daglig transport til læge, hospital og terapi – fast kontrakt giver stabilt volumen",
            "opportunity": "Fast plejehjem-kørsel til sundhed og aktiviteter",
            "action_da": "Ring til plejehjemslederen og tilbyd fast ugentlig kørsel med aftalerabat",
            "contact_title": "Plejehjemsleder",
        },
        {
            "name": "Aarhus Universitet",
            "type": "Uddannelse",
            "address": "Nordre Ringgade 1, 8000 Aarhus C",
            "phone": "+45 87 15 00 00",
            "website": "au.dk",
            "industry": "Videregående uddannelse",
            "size_hint": "38.000 studerende, 8.000 ansatte",
            "potential_score": 75,
            "score_explanation": "Stor international universitetsbefolkning, mange konferencer og gæsteforsker-transport til lufthavn",
            "opportunity": "Personaletransport & internationale gæsters airport-transfer",
            "action_da": "Kontakt AU's rejsebureau eller HR om fast taxa-samarbejde",
            "contact_title": "AU Rejsebureau / HR",
        },
        {
            "name": "Lægerne på Kystvejen",
            "type": "Klinik",
            "address": "Kystvejen 3, 8000 Aarhus C",
            "phone": "+45 86 12 33 44",
            "website": "laegernepaakystvej.dk",
            "industry": "Sundhed & Lægehjælp",
            "size_hint": "Stor praksis, mange ældre og kronisk syge patienter",
            "potential_score": 70,
            "score_explanation": "Ældre patienter med behov for fast hjemtransport – samarbejde med receptionen øger troværdighed",
            "opportunity": "Patient-kørsel & hjemtransport",
            "action_da": "Aftal visitkort ved receptionen og tilbyd fast patient-kørsel til ældre",
            "contact_title": "Praksisleder / Receptionen",
        },
    ],

    "København": [
        {
            "name": "Rigshospitalet",
            "type": "Hospital",
            "address": "Blegdamsvej 9, 2100 København Ø",
            "phone": "+45 35 45 35 45",
            "website": "rigshospitalet.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Danmarks største hospital, 1.200+ senge",
            "potential_score": 95,
            "score_explanation": "Nationalt hospital med konstant patienttransport, ambulante besøg og pårørendes transport – enormt volumen",
            "opportunity": "Fast patienttransport-kontrakt",
            "action_da": "Kontakt indkøbsafdelingen – tilbyd månedlig transportaftale og deltag i Region H's udbud",
            "contact_title": "Indkøbsafdeling / Transportkoordinator",
        },
        {
            "name": "Frederiksberg Kommune",
            "type": "Kommune",
            "address": "Smallegade 1, 2000 Frederiksberg",
            "phone": "+45 38 21 21 21",
            "website": "frederiksberg.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "104.000 borgere, tæt befolket",
            "potential_score": 91,
            "score_explanation": "Velhavende kommune med stort budget til social transport, fast volumen, kommunale udbud regelmæssigt",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud via Udbud.dk – søg på 'Frederiksberg Kommune transport'",
            "contact_title": "Socialforvaltning / Udbudskoordinator",
        },
        {
            "name": "Mærsk HQ (A.P. Møller)",
            "type": "Virksomhed",
            "address": "Esplanaden 50, 1098 København K",
            "phone": "+45 33 63 33 63",
            "website": "maersk.com",
            "industry": "Shipping & Logistik",
            "size_hint": "4.000+ ansatte i København, international executive trafik",
            "potential_score": 89,
            "score_explanation": "Verdenskendt virksomhed med intensiv executive transport til CPH Lufthavn og by-møder",
            "opportunity": "Executive transport & lufthavn-transfer",
            "action_da": "Kontakt facilities manager eller travel desk – tilbyd fast executive taxa-aftale",
            "contact_title": "Travel Manager / Facilities",
        },
        {
            "name": "Hilton Copenhagen Airport",
            "type": "Hotel",
            "address": "Ellehammersvej 20, 2770 Kastrup",
            "phone": "+45 32 50 15 01",
            "website": "hilton.com",
            "industry": "Hotel & Overnatning",
            "size_hint": "382 værelser, direkte lufthavn-adgang",
            "potential_score": 87,
            "score_explanation": "Direkte tilknytning til CPH Lufthavn, konstant behov for by-transfer og lokal transport",
            "opportunity": "By-transfer & airport pick-up aftale",
            "action_da": "Kontakt concierge-chefen – tilbyd fast rabatrate for hotelgæster til Kbh centrum",
            "contact_title": "Concierge / Front Office Manager",
        },
        {
            "name": "Comwell Hotels (3 lokationer)",
            "type": "Hotel",
            "address": "Skt. Thomas Allé 7, 1824 Frederiksberg C",
            "phone": "+45 38 88 18 88",
            "website": "comwell.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "3 Kbh-lokationer, primært konferencegæster",
            "potential_score": 83,
            "score_explanation": "Kædehotel med mange konferencegæster, stabilt transfer-behov til lufthavn og byens attraktioner",
            "opportunity": "Airport transfer + konferencegæstetransport",
            "action_da": "Møde med kædens regional manager – tilbyd samlet aftale for alle 3 lokationer",
            "contact_title": "Regional Manager / Hotelchef",
        },
        {
            "name": "Plejecentret Dæmningen",
            "type": "Plejehjem",
            "address": "Dæmningen 8, 2100 København Ø",
            "phone": "+45 35 27 52 00",
            "website": "kk.dk/plejehjem",
            "industry": "Ældrepleje",
            "size_hint": "Ca. 90 beboere",
            "potential_score": 84,
            "score_explanation": "Kommunalt plejehjem med fast transport til Rigshospitalet og sundhedscentre, stabilt volumen hele året",
            "opportunity": "Fast plejehjem-kørsel til hospital og læge",
            "action_da": "Ring til plejehjemslederen og tilbyd fast ugentlig kørsel med aftalerabat",
            "contact_title": "Plejehjemsleder / Administrationen",
        },
        {
            "name": "Bella Center (MCH)",
            "type": "Venue",
            "address": "Center Boulevard 5, 2300 København S",
            "phone": "+45 32 52 88 11",
            "website": "bellacenter.dk",
            "industry": "Messe & Events",
            "size_hint": "120.000 m² udstillingsareal, 100+ events/år",
            "potential_score": 85,
            "score_explanation": "Danmarks største messehal med konstante events og internationale udstillere – massiv taxiefterspørgsel",
            "opportunity": "Messekørsel & event-transport (officielt partnerskab)",
            "action_da": "Kontakt event-koordinator om officielt taxi-partnersamarbejde for alle messer",
            "contact_title": "Event-koordinator / Kommerciel chef",
        },
        {
            "name": "Nørreport Brasserie",
            "type": "Restaurant",
            "address": "Frederiksborggade 25, 1360 København K",
            "phone": "+45 33 11 55 70",
            "website": "norreportbrasserie.dk",
            "industry": "Restauration",
            "size_hint": "Populær byrestaurant, mange selskaber og festmiddage",
            "potential_score": 68,
            "score_explanation": "Tæt på Nørreport st., firmamiddage og aftenfejringer skaber hjemkørsels-behov – QR-kode i menuen er enkelt",
            "opportunity": "Hjemkørsel efter firmamiddage",
            "action_da": "Aftal QR-kode i menuen og visitkort ved kasseapparatet",
            "contact_title": "Restaurantchef / Ejer",
        },
        {
            "name": "KU – Københavns Universitet",
            "type": "Uddannelse",
            "address": "Nørregade 10, 1165 København K",
            "phone": "+45 35 32 26 26",
            "website": "ku.dk",
            "industry": "Videregående uddannelse",
            "size_hint": "37.000 studerende, 9.000 ansatte",
            "potential_score": 72,
            "score_explanation": "Stort internationalt universitet med konferencer og gæsteforsker-transport, personaletransport ved events",
            "opportunity": "Personaletransport & konferencetransport",
            "action_da": "Kontakt KU's rejseafdeling om fast taxa-samarbejde ved konferencer og gæstebesøg",
            "contact_title": "Rejseafdeling / HR",
        },
        {
            "name": "Hvidovre Hospital",
            "type": "Hospital",
            "address": "Kettegård Allé 30, 2650 Hvidovre",
            "phone": "+45 38 62 38 62",
            "website": "hvidovrehospital.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Ca. 500.000 patientbesøg/år",
            "potential_score": 86,
            "score_explanation": "Stort hospital syd for Kbh, ambulante patienter har brug for fast hjemtransport",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt indkøbsafdelingen og tilmeld til Region H's transportudbud",
            "contact_title": "Indkøbsafdeling",
        },
    ],

    "Odense": [
        {
            "name": "OUH Odense Universitetshospital",
            "type": "Hospital",
            "address": "J.B. Winsløws Vej 4, 5000 Odense C",
            "phone": "+45 65 41 10 00",
            "website": "ouh.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Danmarks 3. største hospital, 800.000+ patientkontakter/år",
            "potential_score": 93,
            "score_explanation": "Stort universitets­hospital med massivt dagligt transport­behov, regionsudbud via Region Syddanmark",
            "opportunity": "Patienttransport-kontrakt (regionalt udbud)",
            "action_da": "Kontakt Region Syddanmarks indkøbsafdeling om transport-udbud",
            "contact_title": "Indkøbsafdeling / Transportkoordinator",
        },
        {
            "name": "Odense Kommune",
            "type": "Kommune",
            "address": "Flakhaven 2, 5000 Odense C",
            "phone": "+45 65 51 50 00",
            "website": "odense.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 205.000 borgere",
            "potential_score": 89,
            "score_explanation": "Stor kommune med fast social transport budget, regelmæssige udbud og voksende befolkning",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud via Udbud.dk – søg på 'Odense Kommune transport'",
            "contact_title": "Socialforvaltning / Udbudsansvarlig",
        },
        {
            "name": "Hotel H.C. Andersen",
            "type": "Hotel",
            "address": "Claus Bergs Gade 7, 5000 Odense C",
            "phone": "+45 66 14 78 00",
            "website": "hotel-hcandersen.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "145 værelser, stor konferencefacilitet",
            "potential_score": 80,
            "score_explanation": "Centralt placeret erhvervshotel med konferencer og erhvervsgæster – transfer til Odense Lufthavn efterspurgt",
            "opportunity": "Airport transfer & konferencegæstetransport",
            "action_da": "Kontakt concierge og tilbyd fast transfer-rate og pjecer i lobbyen",
            "contact_title": "Concierge / Receptionen",
        },
        {
            "name": "Odeon Odense (Kulturhus)",
            "type": "Venue",
            "address": "Odeons Kvarter 1, 5000 Odense C",
            "phone": "+45 63 11 15 00",
            "website": "odeon.dk",
            "industry": "Kultur & Events",
            "size_hint": "Multiscene, 100+ arrangementer/år",
            "potential_score": 78,
            "score_explanation": "Kulturhus med store koncerter og events – taxiefterspørgsel efter aftenforestillinger er høj",
            "opportunity": "Event- og koncerttransport",
            "action_da": "Kontakt eventchefen og tilbyd officielt taxi-partnerskab ved alle arrangementer",
            "contact_title": "Eventchef / Programansvarlig",
        },
        {
            "name": "Syddansk Universitet SDU",
            "type": "Uddannelse",
            "address": "Campusvej 55, 5230 Odense M",
            "phone": "+45 65 50 10 00",
            "website": "sdu.dk",
            "industry": "Videregående uddannelse",
            "size_hint": "27.000 studerende, 5.500 ansatte",
            "potential_score": 74,
            "score_explanation": "Stort regionalt universitet med internationale konferencer, gæsteforskertransport og personalearrangementer",
            "opportunity": "Personaletransport & konferencetransport",
            "action_da": "Kontakt SDU's rejseafdeling eller HR om fast taxa-aftale",
            "contact_title": "Rejseafdeling / HR",
        },
        {
            "name": "Plejehjemmet Elmelunden",
            "type": "Plejehjem",
            "address": "Elmelunden 27, 5000 Odense C",
            "phone": "+45 66 13 30 30",
            "website": "odense.dk/plejehjem",
            "industry": "Ældrepleje",
            "size_hint": "Ca. 70 beboere",
            "potential_score": 82,
            "score_explanation": "Fast behov for transport til OUH og speciallæger – stabil kontrakt mulig",
            "opportunity": "Fast plejehjem-kørsel til hospital og læge",
            "action_da": "Ring til plejehjemslederen og tilbyd fast ugentlig kørsel",
            "contact_title": "Plejehjemsleder",
        },
    ],

    "Aalborg": [
        {
            "name": "Aalborg Universitetshospital",
            "type": "Hospital",
            "address": "Reberbansgade 15, 9000 Aalborg",
            "phone": "+45 97 66 10 00",
            "website": "aalborguniversitetshospital.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Ca. 700.000 patientkontakter/år",
            "potential_score": 92,
            "score_explanation": "Nordjyllands største hospital, dagligt transportbehov, regionalt udbud via Region Nordjylland",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt Region Nordjyllands indkøbsafdeling om transport-udbud",
            "contact_title": "Indkøbsafdeling",
        },
        {
            "name": "Aalborg Kommune",
            "type": "Kommune",
            "address": "Boulevarden 13, 9000 Aalborg",
            "phone": "+45 99 31 31 31",
            "website": "aalborg.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 220.000 borgere",
            "potential_score": 88,
            "score_explanation": "Nordjyllands største kommune, stort social transport budget og regelmæssige udbud",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud via Udbud.dk – søg på 'Aalborg Kommune transport'",
            "contact_title": "Socialforvaltning",
        },
        {
            "name": "Radisson Blu Limfjord Hotel",
            "type": "Hotel",
            "address": "Ved Stranden 14, 9000 Aalborg",
            "phone": "+45 98 16 43 33",
            "website": "radissonblu.com",
            "industry": "Hotel & Overnatning",
            "size_hint": "188 værelser, primært erhverv og konferencer",
            "potential_score": 83,
            "score_explanation": "Centralt erhvervshotel med stor konferencekapacitet, regelmæssig transfer til Aalborg Lufthavn",
            "opportunity": "Airport transfer & konferencegæstetransport",
            "action_da": "Kontakt concierge-chefen og tilbyd fast transfer-rate og pjecer",
            "contact_title": "Concierge / Hotelchef",
        },
        {
            "name": "Aalborg Zoo (Events)",
            "type": "Venue",
            "address": "Mølleparkvej 63, 9000 Aalborg",
            "phone": "+45 98 11 29 00",
            "website": "aalborgzoo.dk",
            "industry": "Oplevelse & Events",
            "size_hint": "350.000+ besøgende/år, aften-events",
            "potential_score": 72,
            "score_explanation": "Populær attraktion med aften-events der skaber taxiefterspørgsel – sæsonaftale mulig",
            "opportunity": "Event-transport ved special-events",
            "action_da": "Kontakt eventafdelingen om transport-aftale ved aftensafaris og private events",
            "contact_title": "Eventafdeling / Direktør",
        },
        {
            "name": "Aalborg Universitet (AAU)",
            "type": "Uddannelse",
            "address": "Fredrik Bajers Vej 7K, 9220 Aalborg Ø",
            "phone": "+45 99 40 99 40",
            "website": "aau.dk",
            "industry": "Videregående uddannelse",
            "size_hint": "21.000 studerende, 4.700 ansatte",
            "potential_score": 73,
            "score_explanation": "Internationalt innovativt universitet med konferencer og gæsteforsker-transport til lufthavn",
            "opportunity": "Personaletransport & konferencetransport",
            "action_da": "Kontakt AAU's rejseafdeling eller HR om fast taxa-aftale",
            "contact_title": "Rejseafdeling / HR",
        },
    ],

    "Vejle": [
        {
            "name": "Vejle Sygehus",
            "type": "Hospital",
            "address": "Beriderbakken 4, 7100 Vejle",
            "phone": "+45 79 40 50 00",
            "website": "vejlesygehus.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Ca. 350.000 patientkontakter/år",
            "potential_score": 90,
            "score_explanation": "Stort sygehus i trekantsbyen, ambulante patienter med dagligt transportbehov",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt indkøbsafdelingen og tilmeld til Region Syds udbud",
            "contact_title": "Indkøbsafdeling",
        },
        {
            "name": "Vejle Kommune",
            "type": "Kommune",
            "address": "Kirketorvet 22, 7100 Vejle",
            "phone": "+45 76 81 00 00",
            "website": "vejle.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 120.000 borgere",
            "potential_score": 86,
            "score_explanation": "Voksende kommune i trekantsbyen, social transport budget og regelmæssige udbud",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud via Udbud.dk – søg på 'Vejle Kommune transport'",
            "contact_title": "Socialforvaltning",
        },
        {
            "name": "Vejle Center Hotel",
            "type": "Hotel",
            "address": "Willy Sørensens Plads 1, 7100 Vejle",
            "phone": "+45 75 82 04 00",
            "website": "vejlecenterhotel.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "101 værelser, central beliggenhed",
            "potential_score": 78,
            "score_explanation": "Centralt hotel i Vejle med erhvervsgæster, transfer til Billund Lufthavn efterspurgt",
            "opportunity": "Airport transfer & erhvervsgæstetransport",
            "action_da": "Kontakt receptionen og tilbyd fast transfer-rate til Billund",
            "contact_title": "Receptionen / Direktør",
        },
        {
            "name": "Legoland (Events & konferencer)",
            "type": "Venue",
            "address": "Nordmarksvej 9, 7190 Billund",
            "phone": "+45 79 33 13 33",
            "website": "legoland.dk",
            "industry": "Turisme & Events",
            "size_hint": "2+ mio. besøgende/år, store konferencer",
            "potential_score": 76,
            "score_explanation": "Verdens­kendt attraktion med store konference-events, executive transport og VIP-kørsel",
            "opportunity": "VIP-transport & konferencetransport",
            "action_da": "Kontakt Legolands events-afdeling om fast VIP-taxa-samarbejde",
            "contact_title": "Events-chef / Kommerciel chef",
        },
    ],

    "Herning": [
        {
            "name": "Herning Sygehus",
            "type": "Hospital",
            "address": "Gl. Landevej 61, 7400 Herning",
            "phone": "+45 99 12 50 00",
            "website": "herningsygehus.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Ca. 250.000 patientkontakter/år",
            "potential_score": 89,
            "score_explanation": "Vestjyllands centrale sygehus, fast ambulant transport­behov, regionalt udbud muligt",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt Region Midtjyllands indkøbsafdeling om transport-udbud",
            "contact_title": "Indkøbsafdeling",
        },
        {
            "name": "Herning Kommune",
            "type": "Kommune",
            "address": "Torvet 5, 7400 Herning",
            "phone": "+45 96 28 28 28",
            "website": "herning.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 90.000 borgere",
            "potential_score": 85,
            "score_explanation": "Midtjysk vækstkommune med social transport og erhvervstransport",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud via Udbud.dk – søg på 'Herning Kommune transport'",
            "contact_title": "Socialforvaltning",
        },
        {
            "name": "MCH Messecenter Herning",
            "type": "Venue",
            "address": "Vardevej 1, 7400 Herning",
            "phone": "+45 99 26 99 26",
            "website": "mch.dk",
            "industry": "Messe & Events",
            "size_hint": "165.000 m² halkapacitet, 75+ events/år",
            "potential_score": 90,
            "score_explanation": "Skandinaviens største messecenter, enorm taxiefterspørgsel ved messe-events og koncerter (DHL, AGRI), officielt partnerskab muligt",
            "opportunity": "Messekørsel & event-transport (officielt partnerskab)",
            "action_da": "Kontakt MCH's event-afdeling om officielt taxi-partnersamarbejde for alle messer",
            "contact_title": "Event-direktør / Kommerciel chef",
        },
        {
            "name": "Hotel Eyde Herning",
            "type": "Hotel",
            "address": "Thomas Petersens Gade 1, 7400 Herning",
            "phone": "+45 97 22 18 00",
            "website": "hoteleyde.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "82 værelser, messenær beliggenhed",
            "potential_score": 80,
            "score_explanation": "Messenært hotel der fyldes op ved MCH-events – transfer til Billund Lufthavn hyppigt efterspurgt",
            "opportunity": "Airport transfer & messegæstetransport",
            "action_da": "Kontakt receptionen om fast transfer-rate og samarbejde under messe-uger",
            "contact_title": "Receptionen / Direktør",
        },
        {
            "name": "FC Midtjylland (MCH Arena)",
            "type": "Venue",
            "address": "Kaj Zartows Vej 5, 7400 Herning",
            "phone": "+45 97 22 29 00",
            "website": "fcm.dk",
            "industry": "Sport & Events",
            "size_hint": "10.700 tilskuere, Superliga + europæiske kampe",
            "potential_score": 84,
            "score_explanation": "Superliga-klub med europæiske kampe og Champions League – massiv taxiefterspørgsel, officielt partnersamarbejde muligt",
            "opportunity": "Kampagnekørsel & event-transport",
            "action_da": "Kontakt FCM's kommercielle afdeling om officielt taxi-partnersamarbejde",
            "contact_title": "Kommerciel chef / Event-manager",
        },
    ],

    "Kolding": [
        {
            "name": "Kolding Sygehus",
            "type": "Hospital",
            "address": "Skovvangen 2-8, 6000 Kolding",
            "phone": "+45 76 36 20 00",
            "website": "koldingsygehus.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Ca. 300.000 patientkontakter/år",
            "potential_score": 91,
            "score_explanation": "Trekantbyens centrale sygehus med stort dagligt transportbehov til ambulante besøg",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt Region Syds indkøbsafdeling om transport-udbud",
            "contact_title": "Indkøbsafdeling",
        },
        {
            "name": "Kolding Kommune",
            "type": "Kommune",
            "address": "Akseltorv 1, 6000 Kolding",
            "phone": "+45 79 79 79 79",
            "website": "kolding.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Ca. 95.000 borgere",
            "potential_score": 87,
            "score_explanation": "Vækstkommune med social transport budget og erhvervstransport til trekantbyens virksomheder",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud via Udbud.dk – søg på 'Kolding Kommune transport'",
            "contact_title": "Socialforvaltning",
        },
        {
            "name": "Scandic Kolding",
            "type": "Hotel",
            "address": "Skovbrynet 1, 6000 Kolding",
            "phone": "+45 76 34 11 00",
            "website": "scandichotels.dk",
            "industry": "Hotel & Overnatning",
            "size_hint": "162 værelser, stor konferencekapacitet",
            "potential_score": 79,
            "score_explanation": "Kædehotel med mange erhvervskonferencer, fast transfer til Billund Lufthavn efterspurgt",
            "opportunity": "Airport transfer & konferencegæstetransport",
            "action_da": "Kontakt hotelchefen – tilbyd fast transfer-rate til Billund",
            "contact_title": "Hotelchef / Receptionen",
        },
        {
            "name": "Trapholt (Kunstmuseum & Events)",
            "type": "Venue",
            "address": "Æblehaven 23, 6000 Kolding",
            "phone": "+45 76 30 05 30",
            "website": "trapholt.dk",
            "industry": "Kultur & Events",
            "size_hint": "100.000+ besøgende/år, firmaarrangementer",
            "potential_score": 70,
            "score_explanation": "Eksklusivt kunstmuseum med firmaarrangementer og fernisering – taxiefterspørgsel ved aftenevents",
            "opportunity": "Event-transport ved private og firmaarrangementer",
            "action_da": "Kontakt eventafdelingen og tilbyd fast taxa-service ved alle aften-events",
            "contact_title": "Eventafdeling / Direktør",
        },
    ],
}

# Generic fallback for unknown cities
def _generic_fallback(city: str) -> List[Dict]:
    return [
        {
            "name": f"Sygehuset i {city}",
            "type": "Hospital",
            "address": f"Sygehusvej 1, {city}",
            "phone": "Ring kommunen for kontakt",
            "website": "rm.dk / regionsyd.dk",
            "industry": "Sundhedsvæsen",
            "size_hint": "Lokalt sygehus med dagligt transportbehov",
            "potential_score": 88,
            "score_explanation": "Sygehuse har altid fast transportbehov for ambulante patienter",
            "opportunity": "Patienttransport-kontrakt",
            "action_da": "Kontakt indkøbsafdelingen og tilmeld til regionens transport-udbud",
            "contact_title": "Indkøbsafdeling",
        },
        {
            "name": f"{city} Kommune",
            "type": "Kommune",
            "address": f"Rådhuset, {city}",
            "phone": "Find på kommunens hjemmeside",
            "website": f"{city.lower()}.dk",
            "industry": "Offentlig forvaltning",
            "size_hint": "Kommunal social transport og handicapkørsel",
            "potential_score": 85,
            "score_explanation": "Kommuner udbyder regelmæssigt social transport – stabilt og forudsigeligt volumen",
            "opportunity": "Social transport & handicapkørsel",
            "action_da": "Afgiv tilbud på næste udbud via Udbud.dk",
            "contact_title": "Socialforvaltning",
        },
        {
            "name": f"Nærliggende Hotel i {city}",
            "type": "Hotel",
            "address": f"Centrum, {city}",
            "phone": "Find lokalt",
            "website": "booking.com",
            "industry": "Hotel & Overnatning",
            "size_hint": "Lokalt hotel med erhvervsgæster",
            "potential_score": 75,
            "score_explanation": "Erhvervshoteller har fast behov for airport-transfer og by-kørsel",
            "opportunity": "Airport transfer & erhvervsgæstetransport",
            "action_da": "Ring til receptionen og tilbyd fast samarbejde og pjecer i lobbyen",
            "contact_title": "Receptionen",
        },
        {
            "name": f"Plejehjemmet i {city}",
            "type": "Plejehjem",
            "address": f"Plejehjem, {city}",
            "phone": "Ring kommunen",
            "website": f"{city.lower()}.dk/plejehjem",
            "industry": "Ældrepleje",
            "size_hint": "Lokalt plejehjem med fast transportbehov",
            "potential_score": 82,
            "score_explanation": "Plejehjem har ugentlig fast transport til speciallæge og hospital",
            "opportunity": "Fast plejehjem-kørsel til hospital og læge",
            "action_da": "Ring til plejehjemslederen og tilbyd fast ugentlig kørsel",
            "contact_title": "Plejehjemsleder",
        },
        {
            "name": f"Lokalt Venue i {city}",
            "type": "Venue",
            "address": f"Centrum, {city}",
            "phone": "Find lokalt",
            "website": "",
            "industry": "Events",
            "size_hint": "Lokalt eventsted",
            "potential_score": 70,
            "score_explanation": "Eventsteder skaber taxiefterspørgsel efter aftenarrangementer",
            "opportunity": "Event-transport",
            "action_da": "Kontakt eventafdelingen og tilbyd taxa-partnerskab",
            "contact_title": "Eventansvarlig",
        },
    ]


class ContractHunterAgent:
    name = "Contract Hunter Agent"

    def run(self, city: str = "København") -> Dict[str, Any]:
        businesses = _CONTRACTS.get(city)
        source = "static"
        if businesses is None:
            businesses = _generic_fallback(city)
            source = "generic_fallback"

        # Apply labels
        enriched = []
        for b in businesses:
            score = b.get("potential_score", 70)
            enriched.append({**b, "priority_label": _label(score)})

        enriched = sorted(enriched, key=lambda x: x["potential_score"], reverse=True)
        top10 = enriched[:10]

        self._log(city, top10)

        return {
            "city": city,
            "total": len(top10),
            "top_contracts": top10,
            "by_type": _group_by_type(top10),
            "highest_score": top10[0]["potential_score"] if top10 else 0,
            "source": source,
            "status": "ok",
        }

    def _log(self, city: str, contracts: List[Dict]) -> None:
        try:
            _LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
            entry = {"city": city, "count": len(contracts), "top": contracts[0]["name"] if contracts else ""}
            with open(_LOG_PATH, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        except Exception as exc:
            log.warning("Kunne ikke skrive contracts_log.jsonl: %s", exc)


def _group_by_type(businesses: List[Dict]) -> Dict[str, List]:
    grouped: Dict[str, List] = {}
    for b in businesses:
        t = b.get("type", "Andet")
        grouped.setdefault(t, []).append({
            "name": b["name"],
            "potential_score": b.get("potential_score", 0),
            "priority_label": b.get("priority_label", _LABEL_MEDIUM),
        })
    return grouped
